### ISSUE TITLE
消融实验的代码改动

### ISSUE THREAD

**Issue by yiranxie233** [liyuke65535/Part-Aware-Transformer#11]
大佬您好,看了您的论文感觉思路很好，最终的结果也可以复现出来，想问一下如果想复现您的消融实验的baseline+CSL需要在代码的哪里进行改动呢？

**Comment by liyuke65535** [comment]
你好，谢谢你对我们工作的关注。

在conifg/default里面设置_C.MODEL.SOFT_LABEL = False (或者在yml文件里面的MODEL下面加一行SOTYFT_LABEL = False)
这样就表示不使用PSD，仅使用CSL。
这份代码命名不是很直观，在未来可能会把名字改成和论文中对应起来的名字以便阅读。

**Comment by yiranxie233** [comment]
好的，非常感谢大佬的回复
